package ca.qc.johnabbott.cs406;


import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class ThreeMensMorris implements Game, Copyable<ThreeMensMorris>{

    // The game table containing current positions.
    public final int TABLESIZE = 3;
    Token[][] gameTable = new Token[TABLESIZE][TABLESIZE];

    // The starting token of the game.
    public final Token starter = Token.WHITE;

    // Keep track of the plays
    private Token lastToken;
    private Token nextToken;

    // Keeping track of the number of turns made.
    public final int MAXTURNS = 6;
    private int turnsMade;;

    // Constructor
    public ThreeMensMorris() {
        lastToken = Token.NONE;
        nextToken = starter;
        turnsMade = 0;
        for(Token[] row : gameTable){
            Arrays.fill(row, Token.NONE);
        }
    }

    // This constructor takes an input similar to the one generated by .toString() as a parameter.
    public ThreeMensMorris(char[] tableState) {
        this();

        int row = -1;
        for (int i = 0; i < tableState.length; i++){
            int col = i % TABLESIZE;
            if(col == 0){
                row += 1;
            }

            char currentChar = tableState[i];
            switch (currentChar){
                case '○':
                    turnsMade++;
                    gameTable[row][col] = Token.WHITE;      // Set the token on the table.
                    lastToken = Token.WHITE;
                    nextToken = Token.BLACK;             // White went so it's Black's turn next.
                    break;
                case '●':
                    turnsMade++;
                    gameTable[row][col] = Token.BLACK;      // Same as above.
                    lastToken = Token.BLACK;
                    nextToken = Token.WHITE;             // Black went so it's White's turn next.
                    break;
                default:
                    gameTable[row][col] = Token.NONE;
                    break;
            }
        }
    }

    // Flag whether the starting phase of TMM can be played anymore.
    public boolean gameOver(){
        if(this.turnsMade == MAXTURNS || this.winner() != Game.Token.NONE)
            return true;

        return false;
    }

    // Methods
    @Override
    public boolean play(int file, int rank) { // 1, 3 => 0, 2
        if(file <= 0 || rank <= 0 || file > TABLESIZE || rank > TABLESIZE){
            throw new RuntimeException("Play index outside the bounds of the game table.");
        }

        // Convert rank and file to array indexes.
        file = file - 1;
        rank = rank - 1;

        // Don't allow a move to occur if all plays have been made OR the game table position is occupied.
        if(turnsMade >= MAXTURNS || gameTable[file][rank] != Token.NONE || this.winner() != Token.NONE) {
            return false;
        }

        gameTable[file][rank] = nextToken;
        turnsMade++;
        lastToken = nextToken;
        nextToken = nextToken.opposite();

        return true;
    }

    // Rank = Row
    private boolean sameRank() {
        for(int i = 0; i < TABLESIZE; i++){
            if(gameTable[i][0] != Token.NONE && gameTable[i][0] == gameTable[i][1] && gameTable[i][1] == gameTable[i][2]) {
                return true;
            }
        }
        return false;
    }

    // File = Column
    private boolean sameFile() {
        for(int i = 0; i < TABLESIZE; i++){
            if(gameTable[0][i] != Token.NONE && gameTable[0][i] == gameTable[1][i] && gameTable[1][i] == gameTable[2][i]){
                return true;
            }
        }
        return false;
    }

    private boolean sameDiagonally() {
        if(lastToken == gameTable[0][0] && lastToken == gameTable[1][1] && lastToken == gameTable[2][2]
        || lastToken == gameTable[0][2] && lastToken == gameTable[1][1] && lastToken == gameTable[2][0]) {
            return true;
        }

        return false;
    }

    @Override
    public Token winner() {
        if(sameDiagonally() || sameRank() || sameFile()) {
            return lastToken;
        }

        return Token.NONE;
    }

    public char[] contentChars() {
        char[] content = new char[TABLESIZE * TABLESIZE];
        int count = 0;
        for(int row = 0; row < TABLESIZE; row++) {
            for(int col = 0; col < TABLESIZE; col++) {
                content[count] = gameTable[row][col].get();
                count++;
            }
        }
        return content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        // Table Contents
        sb.append('[');
        sb.append(contentChars());
        sb.append(']');
        sb.append(' ');

        // Current Turn
        sb.append("turn=");
        sb.append(nextToken);
        sb.append(' ');

        // Winner
        sb.append("winner=");
        sb.append(this.winner().name());

        return sb.toString();
    }

    @Override
    public ThreeMensMorris copy() {
        ThreeMensMorris cp = new ThreeMensMorris();
        cp.turnsMade = this.turnsMade;
        cp.lastToken = this.lastToken;
        cp.nextToken = this.nextToken;
        for(int i = 0; i < TABLESIZE; i++){
            for(int j = 0; j < TABLESIZE; j++){
                cp.gameTable[i][j] = this.gameTable[i][j];
            }
        }
        return cp;
    }

    // Comparison Operators
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ThreeMensMorris that = (ThreeMensMorris) o;

        if (!Arrays.deepEquals(gameTable, that.gameTable)) return false;
        if (starter != that.starter) return false;
        return nextToken == that.nextToken;
    }

    @Override
    public int hashCode() {
        int result = Arrays.deepHashCode(gameTable);
        result = 31 * result + (starter != null ? starter.hashCode() : 0);
        result = 31 * result + (nextToken != null ? nextToken.hashCode() : 0);
        return result;
    }
}
